service: vaccine-appts
useDotenv: true
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dotenv-plugin
 
custom:
  wsgi:
    app: app.app
    packRequirements: false
 
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  lambdaHashingVersion: '20201221'
 
functions:
  app:
    handler: wsgi_handler.handler
    environment:
      GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY}
    events:      
      - http:
          path: /
          method: ANY
          # cors: true
      - http:
          path: /{proxy+}
          method: ANY