service: vaccine-appts
useDotenv: true
 
plugins:
  - serverless-python-requirements
  - serverless-wsgi
 
custom:
  wsgi:
    app: app.app
    packRequirements: false
 
provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${env:SAVED_VACCINE_DATA_BUCKET}/*
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:PutItem
          Resource: arn:aws:dynamodb:${env:CLINIC_DISTANCES_TABLE}
        - Effect: Allow
          Action:
            - dynamodb:Query
          Resource: arn:aws:dynamodb:${env:VACCINE_APPOINTMENTS_TABLE}/*
 
functions:
  app:
    handler: wsgi_handler.handler
    environment:
      GOOGLE_MAPS_API_KEY: ${env:GOOGLE_MAPS_API_KEY}
      SAVED_VACCINE_DATA_BUCKET: ${env:SAVED_VACCINE_DATA_BUCKET}
    events:      
      - http:
          path: /
          method: ANY
          # cors: true
      - http:
          path: /{proxy+}
          method: ANY